"""
Project Euler Problem 2
=======================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.
"""

x = 0
y = 1
z = 1
res = 0

while z < 4000000:
    x = y
    y = z
    z = x + y
    
    if z%2 == 0:
        res += z

print res
    
    
