"""
Project Euler Problem 12
========================

The sequence of triangle numbers is generated by adding the natural
numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
28. The first ten terms would be:

                 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

   1: 1
   3: 1,3
   6: 1,2,3,6
  10: 1,2,5,10
  15: 1,3,5,15
  21: 1,3,7,21
  28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five
divisors.

What is the value of the first triangle number to have over five hundred
divisors?
"""


def findDivisors(n):
    k = 1
    div_res = 0
    max = n
    while k < max/2:
        if n%k == 0:
            print k, n/k
            if k != n/k:
                div_res += 2
            else:
                div_res += 1
            n = n/k
        k+=1
    return div_res
i = 3
n = 3
divisors = 10
while divisors < 5:
    n += i
    divisors = findDivisors(n)
    i += 1

findDivisors(15)

