#! python

import sys, re
import os, importlib
import time, glob

from typing import Tuple, Union, List


# Checks if provided test is numeric 1 to 3 digits
#
def validateTest( test: str ) -> bool:


    if re.match( r'\d{1,3}', test ) is None:
        print( f'The problem number {test} is not a suitable option.' )
        print( 'Try a natural number.' )
        return False

    return True

# Pads the test on the left to be 3 digits
#   
def padTestPath( test: str ) -> str:

    while len( test ) != 3:
        test = '0' + test

    return test

# Processes a test to compare its solution to the answers.
# 
def processTest( my_answer: str, answer: str, duration: float ) -> None:

    if my_answer == answer:
        print( 'CORRECT!' )
        print( f'{my_answer} == {answer}' )
        print( duration )

    else:
        print( 'INCORRECT!' )
        print( f'{my_answer} != {answer}' )

# Gets all of the answers from a provided file
#
def getAnswers():
    answers = {}

    with open( 'data/answers.txt', newline = '' ) as f:
        for line in f:
            m = re.search( r'Problem (\d{3}): (.*)', line )

            problem = m.group(1)
            answer = m.group(2)

            answers[problem] = answer
    return answers        

def log( test: str, flag: str, start_time: float ) -> None:

    log_path = './log/'

    if not os.path.exists( log_path ):
        os.mkdir( log_path )

    log_path += f'{start_time}.txt'

    if not os.path.exists( log_path ):
        with open( log_path, 'w' ) as f:

            f.write( 'Problem\t\tCompleted\t\tPass\n' )

    with open( log_path, 'a' ) as f:
        f.write( f'{test}\t\t\t{flag}\t\tNot sure\n' )


    


# Executes the script at a specific path
#
def getMyAnswer( testpath: str ) -> Tuple[Union[str, None], Union[float, None]]:

    my_answer = None
    duration = None
    if '/' in testpath:
        importpath = testpath.replace( '/', '.' )[:-3]
    else:
        importpath = testpath.replace( '\\', '.' )[:-3]

    if os.path.exists( testpath ):
        module = importlib.import_module( importpath )

        start = time.time()
        try:
            my_answer = str( module.run())
            duration = time.time() - start
        
        except:
            my_answer = 'FAILURE'
            duration = None

    else:

        print( f'The path {testpath} could not be found.' )

    return (my_answer, duration)


if __name__ == "__main__":
    
    args = sys.argv

    if len( args ) <= 1:
        print( 'Please specifiy the problem number to test.' )
        print( 'Ex. ./run 23' )
        exit()

    tests = args[1:]

    all = False
    if tests[0].lower() == 'all':
        tests = list( glob.glob('solutions/*.py' ))
        tests.sort()
        all = True

    answers = getAnswers()
    begin_tests = time.time()
    for test in tests:
        if not all:
            test_is_valid = validateTest( test )

            test = padTestPath( test )

            if test_is_valid:
                testpath = f'solutions/{test}.py'
                my_answer, duration = getMyAnswer( testpath )

        else:
            testpath = test
            test = re.search( r'[\\/](\d{3}).py', testpath ).groups(1)[0]
            my_answer, duration = getMyAnswer( testpath )

        answer = answers[test]
        if my_answer is None:
            log( test, 'Failure', begin_tests )
        else:
            log( test, 'Completed', begin_tests )
        processTest( my_answer, answer, duration )



