""" 
The sequence of triangle numbers is generated by adding the natural numbers. So 
the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten 
terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

from solutions.functions import getfactors
import math

def run() -> int:

	n = 1
	even = 1
	saved = None
	while True:

		first = n//( 2 - even )
		second = ( n + 1 )//( 1 + even )

		if saved is None:
			factors1 = getfactors( first, countonly = True )
		else:
			factors1 = saved
		
		factors2 = getfactors( second, countonly = True )
							
		factorcount = factors1 * factors2

		if factorcount > 500:
			return math.floor( n / 2 * ( n + 1 ))

		even = ( even + 1 ) % 2
			
		n += 1
		saved = factors2


if __name__ == '__main__':
    print( run())